[package]
edition = "2018"
name = "graph-gateway"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4"
eventuals = "0.6.3"
hex = "0.4"
primitive-types = "0.8"
tokio = {version = "1.8", features = ["sync", "time", "macros", "rt-multi-thread"]}
