[workspace]
members = [
    "graph-gateway",
    "indexer-selection",
    "gateway-common",
    "gateway-framework",
]
resolver = "2"

[profile.release]
lto = "thin"

[profile.perf]
inherits = "release"
debug = true


[workspace.dependencies]
anyhow = "1.0"
alloy-primitives = { version = "0.5.3", features = ["serde"] }
graphql = { git = "https://github.com/edgeandnode/toolshed", branch = "main", default-features = false }
graphql-http = { git = "https://github.com/edgeandnode/toolshed.git", branch = "main", features = [
    "http-reqwest",
] }
rand = { version = "0.8", features = ["small_rng"] }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "default-tls",
    "gzip",
] }
serde = { version = "1.0", features = ["derive"] }
siphasher = "1.0.0"
snmalloc-rs = "0.3"
tokio = { version = "1.24", features = [
    "macros",
    "parking_lot",
    "rt-multi-thread",
    "sync",
    "time",
] }
toolshed = { git = "https://github.com/edgeandnode/toolshed", branch = "main" }
thegraph = { git = "https://github.com/edgeandnode/toolshed", branch = "main" }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "parking_lot",
    "json",
] }
