[workspace]
members = ["graph-gateway", "gateway-common", "gateway-framework"]
resolver = "2"

[profile.release]
lto = "thin"

[profile.perf]
inherits = "release"
debug = true

[workspace.dependencies]
anyhow = "1.0"
alloy-primitives = { version = "0.6.4", features = ["serde"] }
axum = { version = "0.6.20", default-features = false, features = [
    "json",
    "tokio",
    "original-uri",
] }
graphql = { git = "https://github.com/edgeandnode/toolshed", tag = "graphql-v0.3.0", default-features = false }
hex = "0.4"
primitive-types = "0.12.2"
rand = { version = "0.8", features = ["small_rng"] }
receipts = { git = "ssh://git@github.com/edgeandnode/receipts.git", rev = "8bc8f13" }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "default-tls",
    "gzip",
] }
secp256k1 = { version = "0.28", default-features = false }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
siphasher = "1.0.1"
thegraph-core = "0.2.2"
thegraph-graphql-http = "0.1.0"
thiserror = "1.0.57"
tokio = { version = "1.36", features = [
    "macros",
    "parking_lot",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
toolshed = { git = "https://github.com/edgeandnode/toolshed", tag = "toolshed-v0.6.0" }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "parking_lot",
    "json",
] }
