[package]
edition = "2018"
name = "graph-gateway"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4" 
cost-model = {git = "ssh://git@github.com/graphprotocol/agora.git", rev = "48bf329"} 
eventuals = "0.6" 
futures = "0.3" 
graphql-parser = {git = "https://github.com/graphql-rust/graphql-parser", rev = "8a759df"} 
hex = "0.4" 
neon-utils = "1.1" # TODO: replace marshalling and remove neon dependency
ordered-float = "2.5" 
primitive-types = "0.8" 
rand = "0.8" 
receipts-allocation = {package = "receipts", git = "ssh://git@github.com/edgeandnode/receipts.git", rev = "ea0ffdd"} 
receipts-transfer = {package = "receipts", git = "ssh://git@github.com/edgeandnode/receipts.git", rev = "f4b756f"} 
secp256k1 = "0.20" 
serde = "1.0" 
serde_json = "1.0" 
tokio = {version = "1.10", features = ["sync", "time", "macros", "rt-multi-thread", "parking_lot"]} 
tree-buf = "0.10" 

[dev-dependencies]
eventuals = {version = "0.6", features = ["trace"]}
rand_distr = "0.4"
