[workspace]
members = ["graph-gateway", "gateway-common", "gateway-framework"]
resolver = "2"

[profile.release]
lto = "thin"

[profile.perf]
inherits = "release"
debug = true

[workspace.dependencies]
anyhow = "1.0"
alloy-primitives = { version = "0.7.1", features = ["serde"] }
alloy-sol-types = "0.7.1"
axum = { git = "https://github.com/tokio-rs/axum", rev = "50c035c", default-features = false, features = [
    "json",
    "tokio",
    "original-uri",
] }
cost-model = { git = "https://github.com/graphprotocol/agora", rev = "deacb09" }
futures = "0.3"
graphql = { git = "https://github.com/edgeandnode/toolshed", tag = "graphql-v0.3.0", default-features = false }
headers = "0.4.0"
hex = "0.4"
indexer-selection = { git = "https://github.com/edgeandnode/candidate-selection", rev = "cf5d179" }
primitive-types = "0.12.2"
rand = { version = "0.8", features = ["small_rng"] }
receipts = { git = "https://github.com/edgeandnode/receipts", rev = "e94e0f1" }
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "default-tls",
    "gzip",
] }
secp256k1 = { version = "0.29", default-features = false }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.116", features = ["raw_value"] }
serde_with = "3.8.1"
siphasher = "1.0.1"
thegraph-core = "0.4.1"
thegraph-graphql-http = "0.2.1"
thiserror = "1.0.59"
tokio = { version = "1.37", features = [
    "macros",
    "parking_lot",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
toolshed = { git = "https://github.com/edgeandnode/toolshed", tag = "toolshed-v0.6.0" }
tower = "0.4.13"
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "parking_lot",
    "json",
] }
