[workspace]
members = ["graph-gateway", "indexer-selection", "prelude"]

[profile.release]
lto = "thin"

[profile.perf]
inherits = "release"
debug = true


[workspace.dependencies]
anyhow = "1.0"
alloy-primitives = { version = "0.3.1", features = ["serde"] }
eventuals = "0.6.7"
rand = { version = "0.8", features = ["small_rng"] }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "default-tls",
    "gzip",
] }
secp256k1 = { version = "0.24", default-features = false }
serde = { version = "1.0", features = ["derive"] }
siphasher = "0.3"
tokio = { version = "1.24", features = [
    "macros",
    "parking_lot",
    "rt-multi-thread",
    "sync",
    "time",
] }
toolshed = { git = "https://github.com/edgeandnode/toolshed", tag = "v0.2.1" }
tracing = { version = "0.1", default-features = false }
