[package]
edition = "2021"
name = "gateway-framework"
version = "0.0.1"

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
ethers = "2.0.11"
eventuals = "0.6.7"
gateway-common = { path = "../gateway-common" }
indexer-selection = { path = "../indexer-selection" }
itertools = "0.12.0"
lazy_static = "1.4.0"
prometheus = "0.13.3"
reqwest.workspace = true
serde.workspace = true
serde_json = "1.0.108"
serde_with = "3.4.0"
thegraph.workspace = true
thiserror = "1.0.51"
tokio.workspace = true
toolshed.workspace = true
tracing.workspace = true
