[package]
edition = "2021"
name = "gateway-framework"
version = "0.0.1"

[features]
# Enable to run protobuf messages code generation at compile time (requires  protoc, etc.).
proto-gen = []

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types = "0.6.3"
anyhow.workspace = true
axum.workspace = true
ethers = "2.0.13"
candidate-selection = { git = "ssh://git@github.com/edgeandnode/candidate-selection.git", rev = "c0b5efa" }
eventuals = "0.6.7"
gateway-common = { path = "../gateway-common" }
graphql-http.workspace = true
headers = "0.3.9"
hex.workspace = true
itertools = "0.12.1"
lazy_static = "1.4.0"
maxminddb = "0.24"
ordered-float = "4.2.0"
primitive-types.workspace = true
prometheus = "0.13.3"
prost = "0.12.3"
prost-types = "0.12.3"
rand.workspace = true
receipts.workspace = true
reqwest.workspace = true
secp256k1.workspace = true
serde.workspace = true
serde_json = "1.0.113"
serde_with = "3.6.1"
siphasher.workspace = true
tap_core = { git = "https://github.com/semiotic-ai/timeline-aggregation-protocol.git", rev = "aa973d1" }
thegraph = { workspace = true, features = ["subgraph-client"] }
thiserror.workspace = true
tokio.workspace = true
tonic = { version = "0.11.0", features = ["tls", "tls-roots"] }
toolshed.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_matches = "1.5.0"
test-with = { version = "0.12.5", default-features = false }

[build-dependencies]
tonic-build = "0.11.0"
