[package]
edition = "2021"
name = "gateway-framework"
version = "0.0.1"

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types = "0.6.4"
anyhow.workspace = true
axum.workspace = true
candidate-selection = { git = "ssh://git@github.com/edgeandnode/candidate-selection.git", rev = "bcd7909" }
ethers = "2.0.14"
eventuals = "0.6.7"
gateway-common = { path = "../gateway-common" }
headers = "0.3.9"
hex.workspace = true
hickory-resolver = "0.24.0"
itertools = "0.12.1"
lazy_static = "1.4.0"
maxminddb = "0.24"
ordered-float = "4.2.0"
primitive-types.workspace = true
prometheus = "0.13.3"
rand.workspace = true
receipts.workspace = true
reqwest.workspace = true
secp256k1.workspace = true
serde.workspace = true
serde_json = { version = "1.0.114", features = ["raw_value"] }
serde_with = "3.6.1"
siphasher.workspace = true
tap_core = { git = "https://github.com/semiotic-ai/timeline-aggregation-protocol.git", rev = "aa973d1" }
thegraph-core = { workspace = true, features = ["subgraph-client"] }
thegraph-graphql-http.workspace = true
thiserror.workspace = true
tokio.workspace = true
toolshed.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url = "2.5.0"

[dev-dependencies]
assert_matches = "1.5.0"
test-with = { version = "0.12.6", default-features = false }
