query CostModels($lastUpdateId: String!) {
  data: costModels(lastUpdateId: $lastUpdateId) {
    updateId
    value {
      deployment
      costModels {
        indexer {
          id
        }
        deployment
        model
        variables
      }
    }
  }
}
