query IndexingStatuses($lastUpdateId: String!) {
  data: indexingStatuses(lastUpdateId: $lastUpdateId) {
    updateId
    value {
      deployment
      statuses {
        indexer {
          id
          url
        }
        deployment
        network
        block {
          number
          hash
        }
        synced
        fatalError {
          message
        }
      }
    }
  }
}
