query Transfers($lastUpdateId: String!, $gatewayId: String!) {
  data: transfers(lastUpdateId: $lastUpdateId, gatewayId: $gatewayId) {
    updateId
    value {
      id
      indexer {
        id
      }
      deployment
      collateral
      signerKey
    }
  }
}
