[package]
edition = "2021"
name = "prelude"
version = "0.0.1"

[dependencies]
anyhow = "1.0"
eventuals = "0.6.7"
hex = "0.4"
primitive-types = "0.12"
rand = { version = "0.8", features = ["small_rng"] }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls-native-roots",
    "trust-dns",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
siphasher = "0.3"
snmalloc-rs = "0.3"
tokio = { version = "1.24", features = [
    "macros",
    "parking_lot",
    "rt-multi-thread",
    "sync",
    "time",
] }
toolshed = { git = "https://github.com/edgeandnode/toolshed", tag = "v0.1.2" }
tracing = { version = "0.1", default-features = false, features = [
    "attributes",
] }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "parking_lot",
    "json",
] }
