[package]
edition = "2021"
name = "indexer-selection"
version = "0.0.1"

[[bin]]
name = "sim"
path = "bin/sim.rs"

[dependencies]
arrayvec = "0.7"
cost-model = { git = "ssh://git@github.com/graphprotocol/agora.git", rev = "6680e61" }
itertools = "0.10"
lazy_static = "1.4"
num-traits = "0.2"
ordered-float = "3.0"
permutation = "0.4"
prelude = { path = "../prelude" }
prometheus = { version = "0.13", default-features = false }
rand_distr = "0.4"
receipts = { git = "ssh://git@github.com/edgeandnode/receipts.git", rev = "89a821c" }
secp256k1 = { version = "0.24", default-features = false }
siphasher = "0.3"

[dev-dependencies]
eventuals = { version = "0.6.7", features = ["trace"] }
