[package]
edition = "2021"
name = "graph-gateway"
version = "15.0.0"

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types = "0.4.2"
anyhow.workspace = true
axum = { version = "0.6.15", default-features = false, features = [
    "json",
    "tokio",
    "original-uri",
] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
ethers = { version = "2.0.10", default-features = false, features = ["abigen"] }
eventuals.workspace = true
faster-hex = "0.8.0"
futures = "0.3"
graph-subscriptions = { git = "https://github.com/edgeandnode/subscription-payments", rev = "334d18b" }
graphql = { git = "https://github.com/edgeandnode/toolshed", tag = "graphql-v0.1.0" }
hex = "0.4"
indexer-selection = { path = "../indexer-selection" }
indoc = "2.0.3"
itertools = "0.11"
lazy_static = "1.4"
maxminddb = "0.23"
prelude = { path = "../prelude" }
primitive-types = "0.12.1"
prometheus = { version = "0.13", default-features = false }
prost = "0.12.1"
rand.workspace = true
rdkafka = { version = "0.36.0", features = ["gssapi", "tracing"] }
reqwest.workspace = true
secp256k1.workspace = true
semver = "1.0"
serde.workspace = true
serde_json = { version = "1.0", features = ["raw_value"] }
serde_with = "3.1"
serde_yaml = "0.9"
simple-rate-limiter = "1.0"
tap_core = { git = "https://github.com/semiotic-ai/timeline-aggregation-protocol", tag = "tap_core-v0.6.0" }
thiserror = "1.0.40"
tokio.workspace = true
toolshed.workspace = true
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["cors"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.16", features = [
    "env-filter",
    "json",
    "parking_lot",
] }
trust-dns-resolver = "0.23.0"
uuid = { version = "1.0", default-features = false, features = ["v4"] }

[dev-dependencies]
assert_matches = "1.5.0"
hyper = "*"
regex = "1.5"
