[package]
edition = "2021"
name = "graph-gateway"
version = "12.0.1"

[dependencies]
actix-cors = "=0.6.0-beta.4"
actix-http = { version = "=3.0.0-beta.14", default-features = false }
actix-web = { version = "=4.0.0-beta.13", default-features = false }
actix-router = "=0.5.0-beta.4"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
futures = "0.3"
futures-util = "0.3"
graph-subscriptions = { git = "https://github.com/edgeandnode/subscription-payments", rev = "b12bd58" }
hdwallet = "0.3"
hex = "0.4"
im = "15.0"
indexer-selection = { path = "../indexer-selection" }
itertools = "0.10"
lazy_static = "1.4"
maxminddb = "0.23"
parking_lot = "0.12.0"
prelude = { path = "../prelude" }
primitive-types = "0.12"
prometheus = { version = "0.13", default-features = false }
rdkafka = { version = "0.29", features = [ "gssapi-vendored", "ssl-vendored" ] }
secp256k1 = { version = "0.24", default-features = false }
semver = "1.0"
serde = "1.0"
serde_json = { version = "1.0", features = ["raw_value"] }
serde_with = { version = "2.2", features = ["chrono_0_4"] }
serde_yaml = "0.9"
simple-rate-limiter = "1.0"
tiny-bip39 = "1.0"
trust-dns-resolver = { version = "0.22", features = ["dns-over-rustls"] }
uuid = { version = "1.0", default-features = false, features = ["v4"] }
prost = "0.11.8"
thiserror = "1.0.40"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json", "parking_lot"] }

[dev-dependencies]
regex = "1.5"
