[package]
edition = "2021"
name = "graph-gateway"
version = "17.1.1"

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types = "0.6.2"
anyhow.workspace = true
axum = { workspace = true, features = ["headers"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
cost-model = { git = "https://github.com/graphprotocol/agora", rev = "3367d76" }
eventuals = "0.6.7"
faster-hex = "0.9.0"
futures = "0.3"
gateway-common = { path = "../gateway-common" }
gateway-framework = { path = "../gateway-framework" }
graphql.workspace = true
graphql-http.workspace = true
headers = "0.3.9"
hickory-resolver = "0.24.0"
indexer-selection = { path = "../indexer-selection" }
indoc = "2.0.4"
itertools = "0.12.0"
pin-project = "1.1.4"
prometheus = { version = "0.13", default-features = false }
prost = "0.12.3"
rand.workspace = true
rdkafka = { version = "0.36.2", features = ["gssapi", "tracing"] }
reqwest.workspace = true
secp256k1.workspace = true
semver.workspace = true
serde.workspace = true
serde_json = { version = "1.0", features = ["raw_value"] }
serde_with = "3.5"
serde_yaml = "0.9"
simple-rate-limiter = "1.0"
snmalloc-rs = "0.3"
thegraph = { workspace = true, features = ["subgraph-client", "subscriptions"] }
thiserror.workspace = true
tokio.workspace = true
toolshed.workspace = true
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["cors"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid = { version = "1.7", default-features = false, features = ["v4"] }

[dev-dependencies]
assert_matches = "1.5.0"
hyper = "0.14.28"
tokio-test = "0.4.3"
tower-test = "0.4.0"
