[package]
edition = "2021"
name = "graph-gateway"
version = "16.1.3"

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types = "0.5.0"
anyhow.workspace = true

chrono = { version = "0.4", default-features = false, features = ["clock"] }
cost-model = { git = "https://github.com/graphprotocol/agora", rev = "3367d76" }
eventuals = "0.6.7"
faster-hex = "0.9.0"
futures = "0.3"
gateway-common = { path = "../gateway-common" }
gateway-framework = { path = "../gateway-framework" }
graph-subscriptions = { git = "https://github.com/edgeandnode/subscription-payments", rev = "334d18b" }
graphql.workspace = true
graphql-http.workspace = true
indexer-selection = { path = "../indexer-selection" }
indoc = "2.0.3"
itertools = "0.12.0"
lazy_static = "1.4"
prometheus = { version = "0.13", default-features = false }
prost = "0.12.1"
rand.workspace = true
rdkafka = { version = "0.35.0", features = ["gssapi", "tracing"] }
reqwest.workspace = true
secp256k1.workspace = true
semver.worksapce = true
serde.workspace = true
serde_json = { version = "1.0", features = ["raw_value"] }
serde_with = "3.1"
serde_yaml = "0.9"
simple-rate-limiter = "1.0"
snmalloc-rs = "0.3"
thegraph = { workspace = true, features = ["subgraph-client", "subscriptions"] }
thiserror = "1.0.56"
tokio.workspace = true
toolshed.workspace = true
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["cors"] }
tracing.workspace = true
tracing-subscriber.workspace = true
trust-dns-resolver = "0.23.0"
uuid = { version = "1.6", default-features = false, features = ["v4"] }
axum.workspace = true

[dev-dependencies]
assert_matches = "1.5.0"
hyper = "0.14.24"
