[package]
edition = "2021"
name = "graph-gateway"
version = "13.4.1"

[dependencies]
axum = { version = "0.6.15", default-features = false, features = [
    "json",
    "tokio",
    "original-uri",
] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
ethers = { version = "2.0.3", default-features = false, features = ["abigen"] }
futures = "0.3"
futures-util = "0.3"
graph-subscriptions = { git = "https://github.com/edgeandnode/subscription-payments", rev = "47c4e9e" }
hdwallet = "0.3"
hex = "0.4"
indexer-selection = { path = "../indexer-selection" }
itertools = "0.11"
lazy_static = "1.4"
maxminddb = "0.23"
parking_lot = "0.12.0"
prelude = { path = "../prelude" }
primitive-types = "0.12"
prometheus = { version = "0.13", default-features = false }
rdkafka = { version = "0.33", features = ["gssapi-vendored", "tracing"] }
secp256k1 = { version = "0.24", default-features = false }
semver = "1.0"
serde = "1.0"
serde_json = { version = "1.0", features = ["raw_value"] }
serde_with = { version = "3.1", features = ["chrono_0_4"] }
serde_yaml = "0.9"
simple-rate-limiter = "1.0"
tiny-bip39 = "1.0"
trust-dns-resolver = "0.22"
uuid = { version = "1.0", default-features = false, features = ["v4"] }
prost = "0.11.8"
thiserror = "1.0.40"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["cors"] }
tracing-subscriber = { version = "0.3.16", features = [
    "env-filter",
    "json",
    "parking_lot",
] }

[dev-dependencies]
hyper = "*"
regex = "1.5"
tokio = { version = "1.28.2", features = ["macros"] }
