[package]
edition = "2021"
name = "graph-gateway"
version = "9.1.0"

[dependencies]
actix-cors = "=0.6.0-beta.4"
actix-http = "=3.0.0-beta.14"
actix-web = "=4.0.0-beta.13"
actix-router = "=0.5.0-beta.4"
async-trait = "0.1"
clap = { version = "3.2", features = ["derive", "env"] }
futures = "0.3"
futures-util = "0.3"
graphql-parser = { git = "https://github.com/graphql-rust/graphql-parser", rev = "8a759df" }
hdwallet = "0.3"
hex = "0.4"
im = "15.0"
indexer-selection = { path = "../indexer-selection" }
itertools = "0.10"
lazy_static = "1.4"
maxminddb = "0.23"
parking_lot = "0.12.0"
prelude = { path = "../prelude" }
primitive-types = "0.12"
prometheus = { version = "0.13", default-features = false }
secp256k1 = { version = "0.24", default-features = false }
semver = "1.0"
serde = "1.0"
serde_json = { version = "1.0", features = ["raw_value"] }
serde_yaml = "0.9"
simple-rate-limiter = "1.0"
tiny-bip39 = "1.0"
tracing = { version = "0.1", default-features = false, features = [
    "attributes",
] }
trust-dns-resolver = { version = "0.22", features = ["dns-over-rustls"] }
url = "2.2"
uuid = { version = "1.0", default-features = false, features = ["v4"] }
rdkafka = { version = "0.28", features = [
    "ssl-vendored",
    "gssapi-vendored",
] }

[dev-dependencies]
eventuals = { version = "0.6.7", features = ["trace"] }
rand = { version = "0.8", features = ["small_rng"] }
regex = "1.5"
