use std::time::SystemTime;

use rand::RngCore;
use tap_graph::v2::{Receipt as TapReceipt, SignedReceipt};
use thegraph_core::{
    CollectionId,
    alloy::{
        dyn_abi::Eip712Domain,
        primitives::{Address, U256},
        signers::local::PrivateKeySigner,
    },
};

pub struct Receipt(SignedReceipt);

impl Receipt {
    pub fn value(&self) -> u128 {
        self.0.message.value
    }

    pub fn collection(&self) -> CollectionId {
        self.0.message.collection_id.into()
    }

    pub fn serialize(&self) -> String {
        serde_json::to_string(&self.0).unwrap()
    }
}

pub struct ReceiptSigner {
    signer: PrivateKeySigner,
    domain: Eip712Domain,
}

impl ReceiptSigner {
    pub fn new(signer: PrivateKeySigner, chain_id: U256, verifying_contract: Address) -> Self {
        Self {
            signer,
            domain: Eip712Domain {
                name: Some("TAP".into()),
                version: Some("1".into()),
                chain_id: Some(chain_id),
                verifying_contract: Some(verifying_contract),
                salt: None,
            },
        }
    }

    pub fn create_receipt(
        &self,
        collection: CollectionId,
        fee: u128,
        payer: Address,
        data_service: Address,
        service_provider: Address,
    ) -> anyhow::Result<Receipt> {
        // Nonce generated with CSPRNG (ChaCha12), to avoid collision with receipts generated by
        // other gateway processes.
        // See https://docs.rs/rand/latest/rand/rngs/index.html#our-generators.
        let nonce = rand::rng().next_u64();

        let timestamp_ns = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
            .try_into()
            .map_err(|_| anyhow::anyhow!("failed to convert timestamp to ns"))?;

        let receipt = TapReceipt {
            collection_id: collection.0.into(),
            payer,
            data_service,
            service_provider,
            timestamp_ns,
            nonce,
            value: fee,
        };
        let signed = SignedReceipt::new(&self.domain, receipt, &self.signer)
            .map_err(|e| anyhow::anyhow!("failed to sign receipt: {:?}", e))?;

        Ok(Receipt(signed))
    }

    pub fn payer_address(&self) -> Address {
        self.signer.address()
    }
}

#[cfg(test)]
mod tests {
    use thegraph_core::{
        alloy::{primitives::address, signers::local::PrivateKeySigner},
        collection_id,
    };

    use super::*;

    #[test]
    fn create_receipt() {
        //* Given
        let secret_key = PrivateKeySigner::from_slice(&[0xcd; 32]).expect("invalid secret key");
        let signer = ReceiptSigner::new(
            secret_key,
            1.try_into().expect("invalid chain id"),
            address!("177b557b12f22bb17a9d73dcc994d978dd6f5f89"),
        );

        let collection =
            collection_id!("89b23fea4e46d40e8a4c6cca723e2a03fdd4bec2a00000000000000000000000");
        let fee = 1000;

        //* When
        let res = signer.create_receipt(
            collection,
            fee,
            address!("1111111111111111111111111111111111111111"), // payer
            address!("2222222222222222222222222222222222222222"), // data_service
            address!("3333333333333333333333333333333333333333"), // service_provider
        );

        //* Then
        let receipt = res.expect("failed to create tap receipt");

        assert_eq!(receipt.value(), fee);
    }
}
